# 数据源配置
#数据库相关配置
spring:
  datasource: 
      url: jdbc:mysql://175.6.73.138:3406/iot_kj?characterEncoding=utf8&useSSL=false
      username: root
      password: root 
 
node2: 
  127.0.0.1
node1:
  175.6.77.235

eureka:
  client:
    serviceUrl:
      defaultZone:
        http://${node1}:8888/eureka/
        


