# 数据源配置
#数据库相关配置
spring:
  datasource: 
      url: jdbc:mysql://175.6.104.133:9017/iot-kj?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: uwh0tnVestNRQ1HEy63d  
 
node2: 
  172.16.20.86
node1:
  172.16.20.100

eureka:
  client:
    serviceUrl:
      defaultZone:
        http://${node2}:8888/eureka/,http://${node1}:8888/eureka/
        
        

logback:
  url:  172.16.20.40:9601