
# 开发环境配置
server:
  # 服务端口
  port: 40000
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    #设置post参数大小
    max-http-post-size: 0
 
# 日志配置
logging:
  level:
    com.cecii: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
# Spring配置
spring:
  profiles: 
    active: ${profiles.active}
  application:
    name: iot-api-smt-device
  datasource:
    druid: 
      # 初始化大小 最小 最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000 # 配置获取连接等待超时的时间
      minEvictableIdleTimeMillis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.cecii
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

  
sms:
  sendSms: 
    Url: http://222.73.117.158/msg/HttpBatchSendSM
    account: vip_zhi168
    password: Tch108569
    
# 代码生成
gen: 
  # 作者
  author: xiangy
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.readboy.ssm.newapp #com.cecii.smtmes
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀(类名不会包含表前缀)
  #tablePrefix: sys_
  #classPrefix : BankPm
  assistUrl: com.readboy.ssm.newapp.util.domain #com.cimr.util
  hasPageOp: true
    